# <center><u>Numpy</u></center> 

## NumPy
 [http://www.numpy.org/] is the core Python package for numerical computing. 
- The main features of NumPy are:
       - n dimensional array object ndarray
       - Vectorized operations and functions which broadcast across arrays for fast computation

**Provides**
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

- **import numpy as np**

### Functions and Methods Overview:-
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.
- **Array Creation:-**
.arange, .array, copy, empty, empty_like, .eye, fromfile, fromfunction, identity, .linspace, logspace, mgrid, ogrid, .ones, ones_like, r, .zeros, zeros_like

- **Attributes:-**
ndarray.flags, ndarray.shape, ndarray.strides, ndarray.ndim, ndarray.data, ndarray.size, ndarray.itemsize, ndarray.nbytes, ndarray.base, ndarray.T, ndarray.real, ndarray.imag, ndarray.flat, ndarray.ctypes, ndarray.dtype

- **Conversions:-**
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

- **Manipulations:-**
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat,
reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

- **Questions:-**
all, any, nonzero, where

- **Ordering:-**
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

- **Operations:-**
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

- **Basic Statistics:-**
cov, mean, std, var

- **Basic Linear Algebra:-**
cross, dot, outer, linalg.svd, vdot

- **Less Basic:-**
Broadcasting rule

- **Universal Functions:-**
apply_along_axis, average, bincount, ceil, clip, conj, corrcoef, diff, floor, inv, lexsort, median, re, round, trace, vectorize

## dtype:
'int64','float64',

# Array Creation
- **Array Creation:-**
.arange, .array, copy, empty, empty_like, .eye, fromfile, fromfunction, identity, .linspace, logspace, mgrid, ogrid, .ones, ones_like, r, .zeros, zeros_like

 ## Function Description:
- **numpy.array(a)**
Create n-dimensional NumPy array from sequence a
- **numpy.linspace(a,b,N)**
Create 1D NumPy array with N equally spaced values from a to b (inclusively)
- **numpy.arange(a,b,step)**
Create 1D NumPy array with values from a to b (exclusively) incremented by step
- **numpy.zeros(N)**
Create 1D NumPy array of zeros of length N
- **numpy.zeros((n,m))**
Create 2D NumPy array of zeros with n rows and m columns
- **numpy.ones(N)**
Create 1D NumPy array of ones of length N
- **numpy.ones((n,m))**
Create 2D NumPy array of ones with n rows and m columns
- **numpy.eye(N)**
Create 2D NumPy array with N rows and N columns with ones on the diagonal (ie. the identity matrix of size N)

## <CENTER>Array</CENTER>

### Array 1D

In [3]:
import numpy as np
a1=[1,2,3,4,5,6,7,8,9]    #type(a1):-<class 'list'> but 1d
print(a1)
a=np.array(a1)            #type(a1):-<class 'array'>
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array 2D

In [62]:
import numpy as np
a1=[[1,2,3],[4,5,6],[7,8,9]]     #type(a1):-<class 'list'> but 2d list
print(a1)
a=np.array(a1)                  #type(a1):-<class 'array'> but 2d array
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array 3D

In [63]:
import numpy as np
#type(a1):-<class 'list'> but 3d list
a1=[[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     
print(a1)
#type(a1):-<class 'array'> but 3d array
a=np.array(a1)                  
a

[[[111, 112, 113], [121, 122, 123], [131, 132, 133]], [[211, 212, 213], [221, 222, 23], [231, 232, 233]], [[311, 312, 313], [321, 322, 323], [331, 332, 333]]]


array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [64]:
#It represents the collection object. It can be a list, tuple
a=((1,2,3),(4,5,6),(7,8,9))    #tupple
a=ndarray=np.array(a)   
b=[[1,2,3],[4,5,6],[7,8,9]]    #list
b=ndarray=np.array(b)   
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
Data=[ [1,2], [3,4] ]
np.array( Data, dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [103]:
Data=[ [1,2], [3,4] ]
np.array( Data, dtype=float )

array([[1., 2.],
       [3., 4.]])

## <CENTER>linspace</CENTER>

In [27]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## <CENTER>arange</CENTER>

In [66]:
a=0
b=5
step=0.5
np.arange(a,b,step) 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [161]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## <CENTER>zeros</CENTER>

In [70]:
N=7
np.zeros(N)
n=2
m=2
np.zeros((n,m))

array([[0., 0.],
       [0., 0.]])

## <CENTER>ones</CENTER>

In [81]:
N=7
np.ones(N) 

array([1., 1., 1., 1., 1., 1., 1.])

In [82]:
n=2
m=2
np.ones((n,m),dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [80]:
# dtype can also be specified
np.ones( (2,3,4), dtype=np.int16 )  

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## <CENTER>eye( identity matrix)</CENTER>

In [5]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ndarray Attributes
- **Attributes:-**
ndarray.flags, ndarray.shape, ndarray.strides, ndarray.ndim, ndarray.data, ndarray.size, ndarray.itemsize, ndarray.nbytes, ndarray.base, ndarray.T, ndarray.real, ndarray.imag, ndarray.flat, ndarray.ctypes, ndarray.dtype


**The following attributes contain information about the memory layout of the array:***

- **ndarray.flags**	    ->Information about the memory layout of the array.
- **ndarray.shape**	    ->Tuple of array dimensions.
- **ndarray.strides**	->Tuple of bytes to step in each dimension when traversing an array.
- **ndarray.ndim**      ->Number of array dimensions.
- **ndarray.data**	    ->Python buffer object pointing to the start of the array’s data.
- **ndarray.size**	    ->Number of elements in the array.
- **ndarray.itemsize**	->Length of one array element in bytes.
- **ndarray.nbytes**	->Total bytes consumed by the elements of the array.
- **ndarray.base**	    ->Base object if memory is from some other object.
- **ndarray.T**	        ->Same as self.transpose(), except that self is returned if self.ndim < 2.
- **ndarray.real**	    ->The real part of the array.
- **ndarray.imag**	    ->The imaginary part of the array.
- **ndarray.flat**	    ->A 1-D iterator over the array.
- **ndarray.ctypes**	->An object to simplify the interaction of the array with the ctypes module.
- **ndarray.dtype**	    ->Data-type of the array’s elements.

In [83]:
a1=[[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     
ndarray=np.array(a1)
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [84]:
ndarray.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [85]:
ndarray.shape

(3, 3, 3)

In [86]:
ndarray.strides

(36, 12, 4)

In [87]:
ndarray.ndim

3

In [88]:
ndarray.data

In [89]:
ndarray.size

27

In [90]:
ndarray.itemsize

4

In [91]:
ndarray.nbytes

108

In [92]:
ndarray.base

In [93]:
ndarray.T

array([[[111, 211, 311],
        [121, 221, 321],
        [131, 231, 331]],

       [[112, 212, 312],
        [122, 222, 322],
        [132, 232, 332]],

       [[113, 213, 313],
        [123,  23, 323],
        [133, 233, 333]]])

In [94]:
ndarray.real

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [95]:
ndarray.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [96]:
ndarray.flat

In [97]:
ndarray.ctypes

In [98]:
ndarray.dtype

dtype('int32')

# Manipulations
- **Manipulations:-**
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat,
reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

In [165]:
A = np.arange( 12 )
B = np.arange( 12 )

In [166]:
A.ravel()  # returns the array, flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [167]:
A.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
A.resize((2,6))
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [169]:
A.item

<function ndarray.item>

In [174]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)


[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [175]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


In [178]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))
A_B = np.hstack((A,B))
C_D = np.hstack((C,D))
T = np.vstack((A_B,C_D))
print(T)


[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


# #Ordering
- **Ordering:-**
argmax, argmin, argsort, max, min, ptp, searchsorted, sort


In [63]:
B = np.array( [2,0,3,4])
B

array([2, 0, 3, 4])

In [64]:
ma=B.argmax()
B[ma]

4

In [65]:
mi=B.argmin()
B[mi]

0

In [66]:
np.argsort(B)  # retun position

array([1, 0, 2, 3], dtype=int64)

In [67]:
#B.min(axis=1)                            # min of each row
B.min()

0

In [68]:
#B.max(axis=1)
B.max()

4

In [69]:
B.ptp()

4

In [70]:
'''
B.sort()    #array([0, 2, 3, 4])
B
'''

'\nB.sort()    #array([0, 2, 3, 4])\nB\n'

# Basic Operations:
- **Operations:-**
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

In [ ]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

# #Basic Statistics
- **Basic Statistics:-**
cov, mean, std, var


In [34]:
B = np.array( [[2,0],[3,4]] )
B

array([[2, 0],
       [3, 4]])

In [35]:
np.cov(B)

array([[ 2. , -1. ],
       [-1. ,  0.5]])

In [36]:
B.mean()

2.25

In [37]:
B.std()

1.479019945774904

In [38]:
B.var()

2.1875

# Basic Linear Algebra
- **Basic Linear Algebra:-**
cross, dot, outer, linalg.svd, vdot

In [98]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [99]:
#np.add(A, B)
A+B

array([[3, 1],
       [6, 5]])

In [100]:
A-B

array([[-1,  1],
       [ 0, -3]])

In [101]:
B**2

array([[ 4,  0],
       [ 9, 16]], dtype=int32)

In [102]:
10*np.sin(A)

array([[8.41470985, 8.41470985],
       [1.41120008, 8.41470985]])

In [103]:
A<35

array([[ True,  True],
       [ True,  True]])

In [104]:
'''
A *= 3
A

o/p:-
array([[ 9,  9,  9,  9],
       [18, 18, 18, 18],
       [27, 27, 27, 27]])
'''

'\nA *= 3\nA\n\no/p:-\narray([[ 9,  9,  9,  9],\n       [18, 18, 18, 18],\n       [27, 27, 27, 27]])\n'

In [105]:
'''
B += A
B

o/p:-
array([[3, 1],
       [6, 5]])
'''

'\nB += A\nB\n\no/p:-\narray([[3, 1],\n       [6, 5]])\n'

In [106]:
A * B                       # elementwise product

array([[2, 0],
       [9, 4]])

In [107]:
A @ B                       # matrix product
#A.dot(B)                    # another matrix product

array([[5, 4],
       [9, 4]])

In [108]:
np.cross(A,B)

array([-2,  9])

array([[0., 6., 8., 5.],
       [6., 5., 3., 2.],
       [7., 3., 9., 6.]])

In [110]:
np.exp(B)

array([[ 7.3890561 ,  1.        ],
       [20.08553692, 54.59815003]])

In [111]:
np.sqrt(B)

array([[1.41421356, 0.        ],
       [1.73205081, 2.        ]])

array([[4., 4.],
       [4., 4.]])

# Operations
- **Operations:-**
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum


In [135]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [136]:
B.cumsum(axis=1)                         # cumulative sum along each row

array([[2, 2],
       [3, 7]], dtype=int32)

In [137]:
B.sum(axis=0)                            # sum of each column

array([5, 4])

# Indexing, Slicing and Iterating:-


In [160]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [70]:
a[2]

8

In [71]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [72]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [76]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000  
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [77]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [162]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998



## Multidimensional:-



The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].


In [79]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [80]:
b[2,3]

23

In [81]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [82]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [83]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [84]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [86]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
               [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [88]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [89]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

# Mathematical Functions

numpy.sin numpy.cos numpy.tan
numpy.exp numpy.log numpy.log10
numpy.arcsin numpy.arccos numpy.arctan

# Note

In [20]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [21]:
#1
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
y

array([1.    , 1.0625, 1.25  , 1.5625, 2.    ])

In [22]:
#2
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [23]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
A


array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [24]:
A[3:]+1

array([], shape=(0, 4), dtype=int32)

In [118]:
0#3
#A@A@A
from numpy.linalg import matrix_power as mpow
mpow(B,3)

array([[ 8,  0],
       [84, 64]])

In [114]:
#4
a = np.floor(10*np.random.random((3,4)))
a

array([[9., 5., 1., 0.],
       [2., 2., 9., 3.],
       [9., 0., 1., 0.]])

In [128]:
a=np.int32(50*np.random.random((3,3)))
a

array([[45, 19, 46],
       [15, 37,  1],
       [40,  5,  3]])

In [ ]:
import numpy as np

a=np.array([10,20,30])
type(a)

a=np.array([10,20,3.5])
a

a=np.array([10,'virat',3.5])
a

a=np.array([10,20,3.5],dtype=np.int8)
a

a=np.array([10,'virat',3.5],dtype=np.int8)

a=np.array([100,125,130],dtype=np.int8)
a

a=np.array([100,125,130],dtype=np.int16)
a

a=np.array([100,125,256],dtype=np.uint8)
a

a=np.array([10,11,12,10,8,9,10,2,3,10])
np.unique(a)
np.bincount(a)

a[a%2==0]

a=a+1
a

b=np.array(range(1,11))
b

c=a+b
c

a=np.arange(1.2,1.9,.1)
a

a=np.zeros(5)
a

a=np.ones(5)
a

a=np.full(5,2)
a

b=np.append(a,100)
b

a
c=np.insert(a,0,20)

c

a

a[0]=200

a

np.max(a)

np.min(a)

a.max()

a.min()

a.sort()

a

a[0]

a[1]

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

type(a)

a

a.size

a.shape

a.