In [2]:
import cv2
import numpy as np
import os

In [3]:
images=[]
labels=[]
for i in range(1,4):
    for j in os.listdir(f'c:/dataset/{i}'):
        img=cv2.imread(f'c:/dataset/{i}/'+j,cv2.IMREAD_GRAYSCALE)
        images.append(img)
        labels.append(i)

In [4]:
X=np.array(images)
y=np.array(labels)

In [5]:
X.shape

(18831, 28, 28)

In [6]:
y.shape

(18831,)

In [7]:
X=X.reshape(len(X),-1)

In [8]:
X.shape

(18831, 784)

In [9]:
from sklearn.decomposition import PCA

In [10]:
pca=PCA(.99)

In [11]:
new_x=pca.fit_transform(X)

In [12]:
new_x.shape

(18831, 300)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
lr=LogisticRegression()

In [15]:
lr.fit(new_x,y)

C:\Users\aditya\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\aditya\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
test_img=cv2.imread('c:/dataset/1.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([1])

In [28]:
test_img=cv2.imread('c:/dataset/2.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([2])

In [29]:
test_img=cv2.imread('c:/dataset/3.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([3])