## <Center>Numpy</Center>

- The main features of NumPy are:
       - n dimensional array object ndarray
       - Vectorized operations and functions which broadcast across arrays for fast computation

**Provides**
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [ ]:
pip install numpy

In [2]:
import numpy as np

In [6]:
np.random.randn(5)

array([ 0.31615956,  0.46555515, -0.70590316, -0.11800382,  0.98442474])

In [9]:
np.random.randn(2, 4)

array([[ 1.74841867, -1.51824424, -1.49097876,  0.28218902],
       [ 1.44832411, -0.80581709, -0.39291713,  1.04338074]])

In [10]:
np.random.randn(2,4,5)

array([[[ 0.72759741,  0.5639058 ,  0.88255534,  0.3260561 ,
          0.4573034 ],
        [-0.36718858,  0.97016935,  0.94022399, -0.50140527,
          0.95732605],
        [-0.6958866 ,  0.69442706,  0.91880142, -1.76426735,
         -1.36218189],
        [ 0.26404876, -2.19821503,  0.20389113, -0.66917793,
         -0.43277519]],

       [[-0.36800137, -1.50730302,  0.69586785,  0.60432167,
         -2.13951281],
        [ 2.1216389 , -0.40435082, -0.15277397,  2.07640133,
         -0.07826316],
        [ 0.86696312, -1.35310134, -0.23261913, -1.88542898,
         -1.29017803],
        [ 0.22780909,  1.41300182, -0.75842742,  0.38137644,
          0.18683147]]])

**Demo**

In [14]:
array_2d_list=np.array([[1,2],[3,4]],dtype=complex )
array_2d_list

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
array_2d_list.dtype

dtype('complex128')

## [Array Creation:](#ArrayCreation)

.arange, .array, copy, empty, empty_like, .eye, fromfile, fromfunction, identity, .linspace, logspace, mgrid, ogrid, .ones, ones_like, r, .zeros, zeros_like

## [Array Attributes](#Attributes)

ndarray.flags, ndarray.shape, ndarray.strides, ndarray.ndim, ndarray.data, ndarray.size, ndarray.itemsize, ndarray.nbytes, ndarray.base, ndarray.T, ndarray.real, ndarray.imag, ndarray.flat, ndarray.ctypes, ndarray.dtype

<a id="ArrayCreation"></a>
### 1. Array Creation:

In [34]:
# np.array()
array_1D_tupple=np.array((1,2,3,4,5,6,7,8,9))  
array_1D_List=np.array([1,2,3,4,5,6,7,8,9])  
array_2D_tupple= np.array(((1,2,3),(4,5,6),(7,8,9)))
array_2D_List=np.array([[1,2,3,4,5,6,7,8,9]])  
array_2D_List=np.array([[1,2,3],[4,5,6],[7,8,9]])  
array_3D_Listc=np.array([[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     )


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_2D_tupple.shape

(3, 3)

In [20]:
#linspace
init=0
final=1
no_split=20       # default 100
a=np.linspace(init,final,no_split)  
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [38]:
a.shape

(20,)

In [24]:
# arange
init=0
final=5
step=0.1
a=np.arange(init)
b=np.arange(init,final)
c=np.arange(init,final,step)
c

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [41]:
# zeros
a=np.zeros(7)
b=np.zeros((2,2))
c=np.zeros( (3,3,4), dtype=np.int16 )  

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [26]:
# ones
a=np.ones(7) 
b=np.ones((7,7),dtype=np.int16)
c=np.ones( (2,3,4), dtype=np.int16 )  
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [28]:
# eye
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<a id="Attributes"></a>
### 2. Attributes:

In [35]:
a1=[[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     
ndarray=np.array(a1)
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [38]:
ndarray.dtype

dtype('int32')

In [39]:
ndarray.shape

(3, 3, 3)

In [40]:
ndarray.ndim

3

In [41]:
ndarray.size

27

In [44]:
ndarray.T

array([[[111, 211, 311],
        [121, 221, 321],
        [131, 231, 331]],

       [[112, 212, 312],
        [122, 222, 322],
        [132, 232, 332]],

       [[113, 213, 313],
        [123,  23, 323],
        [133, 233, 333]]])

In [47]:
ndarray.real

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [48]:
ndarray.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [36]:
# ndarray.flags
# ndarray.data
# ndarray.nbytes
# ndarray.strides
# ndarray.itemsize
# ndarray.flat
# ndarray.ctypes
# ndarray.base

### 3. Manipulations:

    array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

In [50]:
A = np.arange( 12 )
B = np.arange( 12 )

In [51]:
A.ravel()  # returns the array, flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
A.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A.resize((2,6))
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)


[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [40]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


In [46]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))
A_B = np.hstack((A,B))
C_D = np.hstack((C,D))
T = np.vstack((A_B,C_D))
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [47]:
#A.item

### 4. Ordering:

In [48]:
B = np.array( [2,0,3,25,5])
B.argmax()

3

In [77]:
# argmax() return position
B[B.argmax()]

25

In [78]:
B[B.argmin()]

0

In [79]:
np.argsort(B)  # retun position

array([1, 0, 2, 4, 3], dtype=int64)

In [80]:
#B.max(axis=1)
B.max()

25

In [81]:
#B.min(axis=1)                            # min of each row
B.min()

0

In [87]:
#Peak-to-peak (maximum - minimum) value along the given axis.
# B.ptp(1) #in 2d
B.ptp()

25

In [94]:
# B.searchsorted 
B.searchsorted(6)

5

In [95]:
B.sort()    #array([0, 2, 3, 4])
B

array([ 0,  2,  3,  5, 25])

### 5. Operations:

    choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

In [51]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )
B

array([[2, 0],
       [3, 4]])

In [52]:
#[[2,0]
#[(2+3),(0+4)]]
B.cumsum(axis=0)                         # cumulative sum along each row

array([[2, 0],
       [5, 4]], dtype=int32)

In [54]:
B.sum(axis=1)                            # sum of each column

array([2, 7])

### 6. Basic Statistics: 
```cov, mean, std, var
```


In [53]:
B = np.array( [[2,0],[3,4]] )
B

array([[2, 0],
       [3, 4]])

In [54]:
np.cov(B)

array([[ 2. , -1. ],
       [-1. ,  0.5]])

In [55]:
B.mean()

2.25

In [56]:
B.std()

1.479019945774904

In [57]:
B.var()

2.1875

### 7. Basic Linear Algebra:

    cross, dot, outer, linalg.svd, vdot

In [58]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [59]:
#np.add(A, B)
A+B

array([[3, 1],
       [6, 5]])

In [60]:
A-B

array([[-1,  1],
       [ 0, -3]])

In [61]:
B**2

array([[ 4,  0],
       [ 9, 16]], dtype=int32)

In [62]:
10*np.sin(A)

array([[8.41470985, 8.41470985],
       [1.41120008, 8.41470985]])

In [63]:
A<35

array([[ True,  True],
       [ True,  True]])

In [64]:
A *= 3   
A

array([[3, 3],
       [9, 3]])

In [65]:
B += A
B

array([[ 5,  3],
       [12,  7]])

In [53]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [55]:
A

array([[1, 1],
       [3, 1]])

In [56]:
B

array([[2, 0],
       [3, 4]])

In [59]:
A * B                       # elementwise product

array([[2, 0],
       [9, 4]])

In [57]:
A @ B                       # matrix product
#A.dot(B)                    # another matrix product

array([[5, 4],
       [9, 4]])

In [58]:
np.cross(A,B)

array([-2,  9])

np.exp(B)

In [70]:
np.sqrt(B)

array([[2.23606798, 1.73205081],
       [3.46410162, 2.64575131]])

In [61]:
import math as mt

In [63]:
math.pi

3.141592653589793

In [64]:
mt.pi

3.141592653589793

# Indexing, Slicing and Iterating:-

In [67]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [68]:
a[2]

8

In [69]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [70]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [71]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000  
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [72]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [75]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [74]:
for i in a:
    print(i**(1/3))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


d:\pythonenv\base3.7\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  



## Multidimensional:-



The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].


In [86]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [88]:
def f(x,y):
    return 10*x+y
f(5,4)

54

In [95]:
# b=np.arange(0,30)
# b=b.reshape(15,2)
# for i in b:
#     c=tuple(i)
#     b = np.fromfunction(f,c,dtype=int)
# #     print(b)

In [85]:
b[2,3]

23

In [86]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [87]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [88]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [89]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [90]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
               [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [91]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [92]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

# Mathematical Functions

numpy.sin numpy.cos numpy.tan
numpy.exp numpy.log numpy.log10
numpy.arcsin numpy.arccos numpy.arctan

# Note

In [93]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [94]:
#1
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
y

array([1.    , 1.0625, 1.25  , 1.5625, 2.    ])

In [95]:
#2
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [96]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [97]:
A[3:]+1

array([], shape=(0, 4), dtype=int32)

In [98]:
0#3
#A@A@A
from numpy.linalg import matrix_power as mpow
mpow(B,3)

array([[ 8,  0],
       [84, 64]])

In [99]:
#4
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 8., 7., 3.],
       [3., 1., 6., 7.],
       [4., 1., 8., 9.]])

In [100]:
a=np.int32(50*np.random.random((3,3)))
a

array([[ 5,  8, 37],
       [22,  4,  4],
       [12, 27, 10]])

In [105]:
a=np.array([10,11,12,10,8,9,10,2,3,10])
a

array([10, 11, 12, 10,  8,  9, 10,  2,  3, 10])

In [101]:

b=np.append(a,100)
b


array([  5,   8,  37,  22,   4,   4,  12,  27,  10, 100])

In [103]:

c=np.insert(a,0,20)
c

array([20,  5,  8, 37, 22,  4,  4, 12, 27, 10])

In [107]:
a=np.full(5,2)
a

array([2, 2, 2, 2, 2])

In [108]:
np.unique(a)

array([2])

In [109]:
np.bincount(a)

array([0, 0, 5], dtype=int64)