## <Center>Numpy</Center>

- The main features of NumPy are:
       - n dimensional array object ndarray
       - Vectorized operations and functions which broadcast across arrays for fast computation

**Provides**
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

**Install**

In [ ]:
pip install numpy

**import**

In [2]:
import numpy as np

**Demo**

In [14]:
array_2d_list=np.array([[1,2],[3,4]],dtype=complex )
array_2d_list

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
array_2d_list.dtype

dtype('complex128')

## [Array Creation:](#ArrayCreation)

.arange, .array, copy, empty, empty_like, .eye, fromfile, fromfunction, identity, .linspace, logspace, mgrid, ogrid, .ones, ones_like, r, .zeros, zeros_like

## [Array Attributes](#Attributes)

ndarray.flags, ndarray.shape, ndarray.strides, ndarray.ndim, ndarray.data, ndarray.size, ndarray.itemsize, ndarray.nbytes, ndarray.base, ndarray.T, ndarray.real, ndarray.imag, ndarray.flat, ndarray.ctypes, ndarray.dtype

### [Array Manipulations](#Manipulations)

array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

### [Array Ordering](#Ordering)


<a id="ArrayCreation"></a>
### 1. Array Creation:

In [3]:
# np.random.randn() 
np.random.randn(2)      # return 1-d array
np.random.randn(2,2)    # return 2-d array
np.random.randn(2,2,2)  # return 2-d array

array([[[-0.88564216,  0.35902651],
        [-0.00641008,  0.76456797]],

       [[-0.50845799, -0.03694757],
        [ 1.50261677, -0.62773501]]])

In [4]:
# np.array()

#1D
np.array([1,2,3,4,5,6,7,8,9])  

#2D
np.array([[1,2,3,4,5,6,7,8,9]])  
np.array([[1,2,3],[4,5,6],[7,8,9]])

#3D
np.array([[[111,112,113],[121,122,123]], 
          [[211,212,213],[221,222,23]],
          [[321,322,323],[331,332,333]]])


array([[[111, 112, 113],
        [121, 122, 123]],

       [[211, 212, 213],
        [221, 222,  23]],

       [[321, 322, 323],
        [331, 332, 333]]])

In [7]:
# np.linspace() 

np.linspace(start=0,stop=50,num=20)  

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [12]:
# np.arange()

np.arange(20)                      # 0 to n return array
np.arange(start=5,stop=10)
np.arange(start=5,stop=10,step=0.5 )   # 0.5

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
# np.zeros()

np.zeros(7)             # 1-d return array all value is 0 in all index
np.zeros((2,2))
np.zeros((2,2,2), dtype=np.int16 )  

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int16)

In [17]:
# np.ones() 

np.ones(7) 
np.ones((2,2),dtype=np.int16)
np.ones((2,2,2), dtype=np.int16 )  

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [26]:
# eye
np.eye(3)  # return  2D

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<a id="Attributes"></a>
### 2. Attributes:

In [28]:
ndarray=np.random.randn(2,2,2)

In [29]:
ndarray.dtype

dtype('float64')

In [31]:
ndarray.shape

(2, 2, 2)

In [32]:
ndarray.ndim

3

In [33]:
ndarray.size

8

In [34]:
ndarray.T

array([[[-1.46901207, -0.86681247],
        [ 0.53836244,  0.65736978]],

       [[ 0.2152888 ,  0.10573428],
        [-0.44681195,  0.80838374]]])

In [35]:
ndarray.real

array([[[-1.46901207,  0.2152888 ],
        [ 0.53836244, -0.44681195]],

       [[-0.86681247,  0.10573428],
        [ 0.65736978,  0.80838374]]])

In [36]:

ndarray.imag

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

<a id="Manipulations"></a>
### 3. Manipulations:

In [54]:
A = np.arange(12)
B = np.arange(12)

In [56]:
A.ravel()  # returns the array 1D, flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
A.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
A.resize((2,6))
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [63]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


In [64]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))
A_B = np.hstack((A,B))
C_D = np.hstack((C,D))
T = np.vstack((A_B,C_D))
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


<a id="Ordering"></a>
### 4. Ordering:

In [66]:
B = np.array( [2,0,3,25,5])
B.argmax()

3

In [67]:
# argmax() return position
B[B.argmax()]

25

In [68]:
B[B.argmin()]

0

In [69]:
np.argsort(B)  # retun position

array([1, 0, 2, 4, 3])

In [70]:
#B.max(axis=1)
B.max()

25

In [71]:
#B.min(axis=1)                            # min of each row
B.min()

0

In [72]:
#Peak-to-peak (maximum - minimum) value along the given axis.
# B.ptp(1) #in 2d
B.ptp()

25

In [73]:
# B.searchsorted 
B.searchsorted(6)

5

In [74]:
B.sort()    #array([0, 2, 3, 4])
B

array([ 0,  2,  3,  5, 25])

### 5. Operations:
    choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

In [77]:
B = np.array( [[2,0],[3,1],[3,1]])
B

array([[2, 0],
       [3, 1],
       [3, 1]])

In [79]:
#[[2,0]
#[(2+3),(0+1)]]
#[(2+3+3),(0+1+1)]]
B.cumsum(axis=0)                         # cumulative sum along each row

array([[2, 0],
       [5, 1],
       [8, 2]])

In [54]:
B.sum(axis=1)                            # sum of each column

array([2, 7])

### 6. Basic Statistics: 
```cov, mean, std, var
```


In [80]:
B = np.array( [[2,0],[3,4]] )
B

array([[2, 0],
       [3, 4]])

In [81]:
np.cov(B)

array([[ 2. , -1. ],
       [-1. ,  0.5]])

In [55]:
B.mean()

2.25

In [56]:
B.std()

1.479019945774904

In [57]:
B.var()

2.1875

### 7. Basic Linear Algebra:

    cross, dot, outer, linalg.svd, vdot

In [58]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [59]:
#np.add(A, B)
A+B

array([[3, 1],
       [6, 5]])

In [60]:
A-B

array([[-1,  1],
       [ 0, -3]])

In [61]:
B**2

array([[ 4,  0],
       [ 9, 16]], dtype=int32)

In [62]:
10*np.sin(A)

array([[8.41470985, 8.41470985],
       [1.41120008, 8.41470985]])

In [63]:
A<35

array([[ True,  True],
       [ True,  True]])

In [64]:
A *= 3   
A

array([[3, 3],
       [9, 3]])

In [65]:
B += A
B

array([[ 5,  3],
       [12,  7]])

In [53]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [55]:
A

array([[1, 1],
       [3, 1]])

In [56]:
B

array([[2, 0],
       [3, 4]])

In [59]:
A * B                       # elementwise product

array([[2, 0],
       [9, 4]])

In [57]:
A @ B                       # matrix product
#A.dot(B)                    # another matrix product

array([[5, 4],
       [9, 4]])

In [58]:
np.cross(A,B)

array([-2,  9])

np.exp(B)

In [70]:
np.sqrt(B)

array([[2.23606798, 1.73205081],
       [3.46410162, 2.64575131]])

In [61]:
import math as mt

In [63]:
math.pi

3.141592653589793

In [64]:
mt.pi

3.141592653589793