# Indexing, Slicing and Iterating:-

In [67]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [68]:
a[2]

8

In [69]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [70]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [71]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000  
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [72]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [75]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [74]:
for i in a:
    print(i**(1/3))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


d:\pythonenv\base3.7\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  



## Multidimensional:-



The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].


In [86]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [88]:
def f(x,y):
    return 10*x+y
f(5,4)

54

In [95]:
# b=np.arange(0,30)
# b=b.reshape(15,2)
# for i in b:
#     c=tuple(i)
#     b = np.fromfunction(f,c,dtype=int)
# #     print(b)

In [85]:
b[2,3]

23

In [86]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [87]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [88]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [89]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [90]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
               [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [91]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [92]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

# Mathematical Functions

numpy.sin numpy.cos numpy.tan
numpy.exp numpy.log numpy.log10
numpy.arcsin numpy.arccos numpy.arctan

# Note

In [93]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [94]:
#1
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
y

array([1.    , 1.0625, 1.25  , 1.5625, 2.    ])

In [95]:
#2
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [96]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [97]:
A[3:]+1

array([], shape=(0, 4), dtype=int32)

In [98]:
0#3
#A@A@A
from numpy.linalg import matrix_power as mpow
mpow(B,3)

array([[ 8,  0],
       [84, 64]])

In [99]:
#4
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 8., 7., 3.],
       [3., 1., 6., 7.],
       [4., 1., 8., 9.]])

In [100]:
a=np.int32(50*np.random.random((3,3)))
a

array([[ 5,  8, 37],
       [22,  4,  4],
       [12, 27, 10]])

In [105]:
a=np.array([10,11,12,10,8,9,10,2,3,10])
a

array([10, 11, 12, 10,  8,  9, 10,  2,  3, 10])

In [101]:

b=np.append(a,100)
b


array([  5,   8,  37,  22,   4,   4,  12,  27,  10, 100])

In [103]:

c=np.insert(a,0,20)
c

array([20,  5,  8, 37, 22,  4,  4, 12, 27, 10])

In [107]:
a=np.full(5,2)
a

array([2, 2, 2, 2, 2])

In [108]:
np.unique(a)

array([2])

In [109]:
np.bincount(a)

array([0, 0, 5], dtype=int64)