In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('c:/dataset/online_ads.csv')

In [3]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [4]:
df.shape

(400, 4)

In [5]:
df=pd.get_dummies(df)

In [6]:
df.shape

(400, 5)

In [7]:
df.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Female', 'Gender_Male'], dtype='object')

In [8]:
df.head()

Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0              0            1
1   35            20000          0              0            1
2   26            43000          0              1            0
3   27            57000          0              1            0
4   19            76000          0              0            1

In [11]:
X=df.loc[:,('Age','EstimatedSalary','Gender_Female','Gender_Male')].values

In [12]:
y=df.loc[:,'Purchased'].values

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc=StandardScaler()

In [16]:
X_new=sc.fit_transform(X.astype(float))

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X_new,y)

In [19]:
X_train.shape

(300, 4)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
log=LogisticRegression()

In [22]:
log.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
prob=log.predict_proba(X_train)

In [39]:
y_train[12]

1

In [41]:
prob[12]

array([0.57241321, 0.42758679])

In [36]:
pred=log.predict(X_train)

In [42]:
pred[12]

0

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_train,pred)

0.83

In [53]:
mypred=[]
for pb in prob:
    if(pb[0]>=.65):
        mypred.append(0)
    else:
        mypred.append(1)

In [54]:
accuracy_score(y_train,mypred)

0.8533333333333334

In [55]:
test_prob=log.predict_proba(X_test)

In [56]:
test_prob[0]

array([0.96461564, 0.03538436])

In [57]:
test_pred=log.predict(X_test)

In [58]:
test_pred[0]

0

In [59]:
accuracy_score(y_test,test_pred)

0.9

In [60]:
X_test[0]

array([-0.44461362, -1.22576253,  0.98019606, -0.98019606])

In [61]:
log.coef_

array([[ 2.12950086,  0.96823536, -0.11275924,  0.11275924]])

In [62]:
log.intercept_

array([-0.9507758])

In [64]:
cont_y=log.coef_[0][0]*X_test[0][0]+log.coef_[0][1]*X_test[0][1]+log.coef_[0][2]*X_test[0][2]+log.coef_[0][3]*X_test[0][3]+log.intercept_[0]

In [65]:
cont_y

-3.305459831344623

In [66]:
import numpy as np

In [67]:
class_y=1/(1+np.exp(-cont_y))

In [68]:
class_y

0.035384359164757