In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30])

In [3]:
type(a)

numpy.ndarray

In [4]:
a=np.array([10,20,3.5])

In [5]:
a

array([10. , 20. ,  3.5])

In [6]:
a=np.array([10,'virat',3.5])

In [7]:
a

array(['10', 'virat', '3.5'], dtype='<U11')

In [8]:
a=np.array([10,20,3.5],dtype=np.int8)

In [9]:
a

array([10, 20,  3], dtype=int8)

In [10]:
a=np.array([10,'virat',3.5],dtype=np.int8)

ValueError: invalid literal for int() with base 10: 'virat'

In [12]:
a=np.array([100,125,130],dtype=np.int8)

In [13]:
a

array([ 100,  125, -126], dtype=int8)

In [14]:
a=np.array([100,125,130],dtype=np.int16)

In [15]:
a

array([100, 125, 130], dtype=int16)

In [20]:
a=np.array([100,125,256],dtype=np.uint8)

In [21]:
a

array([100, 125,   0], dtype=uint8)

In [22]:
a=np.array([10,11,12,10,8,9,10,2,3,10])

In [23]:
np.unique(a)

array([ 2,  3,  8,  9, 10, 11, 12])

In [24]:
np.bincount(a)

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 4, 1, 1], dtype=int64)

In [25]:
a[a%2==0]

array([10, 12, 10,  8, 10,  2, 10])

In [26]:
a=a+1

In [27]:
a

array([11, 12, 13, 11,  9, 10, 11,  3,  4, 11])

In [28]:
a

array([11, 12, 13, 11,  9, 10, 11,  3,  4, 11])

In [41]:
b=np.array(range(1,11))

In [33]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
c=a+b

In [35]:
c

array([12, 14, 16, 15, 14, 16, 18, 11, 13, 21])

In [38]:
a=np.arange(1.2,1.9,.1)

In [39]:
a

array([1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8])

In [45]:
a=np.zeros(5)

In [46]:
a

array([0., 0., 0., 0., 0.])

In [47]:
a=np.ones(5)

In [48]:
a

array([1., 1., 1., 1., 1.])

In [49]:
a=np.full(5,2)

In [50]:
a

array([2, 2, 2, 2, 2])

In [53]:
b=np.append(a,100)

In [54]:
a

array([2, 2, 2, 2, 2])

In [55]:
b

array([  2,   2,   2,   2,   2, 100])

In [56]:
c=np.insert(a,0,20)

In [57]:
c

array([20,  2,  2,  2,  2,  2])

In [58]:
a

array([2, 2, 2, 2, 2])

In [59]:
a[0]=200

In [60]:
a

array([200,   2,   2,   2,   2])

In [61]:
np.max(a)

200

In [62]:
np.min(a)

2

In [63]:
a.max()

200

In [64]:
a.min()

2

In [65]:
a.sort()

In [66]:
a

array([  2,   2,   2,   2, 200])

In [67]:
a[0]

2

In [68]:
a[1]

2

In [69]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
type(a)

numpy.ndarray

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a.size

9

In [73]:
a.shape

(3, 3)

In [ ]:
a.