- The main features of NumPy are:
       - n dimensional array object ndarray
       - Vectorized operations and functions which broadcast across arrays for fast computation

**Provides**
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [2]:
import numpy as np

### 1. Array Creation:

    .arange, .array, copy, empty, empty_like, .eye, fromfile, fromfunction, identity, .linspace, logspace, mgrid, ogrid, .ones, ones_like, r, .zeros, zeros_like

In [3]:
np.array([1,2,3,4,5,6,7,8,9]) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array(((1,2,3),(4,5,6),(7,8,9)))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]]  )  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.array([[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     )

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [7]:
np.array( [ [1,2], [3,4] ], dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [8]:
np.array( [ [1,2], [3,4] ], dtype=float )

array([[1., 2.],
       [3., 4.]])

**linspace**

In [9]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**arange**

In [10]:
a=0
b=5
step=0.1
np.arange(a,b,step) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [11]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

**zeros**

In [12]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

**ones**

In [14]:
np.ones(7) 

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((7,7),dtype=np.int16)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [16]:
np.ones( (2,3,4), dtype=np.int16 )  

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

**eye( identity matrix)**

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2. Attributes:
    
    ndarray.flags, ndarray.shape, ndarray.strides, ndarray.ndim, ndarray.data, ndarray.size, ndarray.itemsize, ndarray.nbytes, ndarray.base, ndarray.T, ndarray.real, ndarray.imag, ndarray.flat, ndarray.ctypes, ndarray.dtype


In [18]:
a1=[[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,23],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]]     
ndarray=np.array(a1)

In [19]:
ndarray.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [20]:
ndarray.shape

(3, 3, 3)

In [21]:
ndarray.strides

(36, 12, 4)

In [22]:
ndarray.ndim

3

In [23]:
ndarray.data

In [24]:
ndarray.size

27

In [25]:
ndarray.itemsize

4

In [26]:
ndarray.nbytes

108

In [27]:
ndarray.base

In [28]:
ndarray.T

array([[[111, 211, 311],
        [121, 221, 321],
        [131, 231, 331]],

       [[112, 212, 312],
        [122, 222, 322],
        [132, 232, 332]],

       [[113, 213, 313],
        [123,  23, 323],
        [133, 233, 333]]])

In [29]:
ndarray.real

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222,  23],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [30]:
ndarray.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [31]:
ndarray.flat

In [32]:
ndarray.ctypes

In [33]:
ndarray.dtype

dtype('int32')

### 3. Manipulations:
    
    array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

In [34]:
A = np.arange( 12 )
B = np.arange( 12 )

In [35]:
A.ravel()  # returns the array, flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
A.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A.resize((2,6))
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
A.item

<function ndarray.item>

In [39]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)


[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [40]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


In [41]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))
A_B = np.hstack((A,B))
C_D = np.hstack((C,D))
T = np.vstack((A_B,C_D))
print(T)


[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


### 4. Ordering:

    argmax, argmin, argsort, max, min, ptp, searchsorted, sort


In [42]:
B = np.array( [2,0,3,4])

In [43]:
ma=B.argmax()
B[ma]

4

In [44]:
mi=B.argmin()
B[mi]

0

In [45]:
np.argsort(B)  # retun position

array([1, 0, 2, 3], dtype=int64)

In [46]:
#B.min(axis=1)                            # min of each row
B.min()

0

In [47]:
#B.max(axis=1)
B.max()

4

In [48]:
B.ptp()

4

In [49]:
B.sort()    #array([0, 2, 3, 4])
B

array([0, 2, 3, 4])

### 5. Operations:

    choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

In [135]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [51]:
B.cumsum(axis=0)                         # cumulative sum along each row

array([0, 2, 5, 9], dtype=int32)

In [52]:
B.sum(axis=0)                            # sum of each column

9

### 6. Basic Statistics:
    
    cov, mean, std, var


In [53]:
B = np.array( [[2,0],[3,4]] )
B

array([[2, 0],
       [3, 4]])

In [54]:
np.cov(B)

array([[ 2. , -1. ],
       [-1. ,  0.5]])

In [55]:
B.mean()

2.25

In [56]:
B.std()

1.479019945774904

In [57]:
B.var()

2.1875

### 7. Basic Linear Algebra:

    cross, dot, outer, linalg.svd, vdot

In [58]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [59]:
#np.add(A, B)
A+B

array([[3, 1],
       [6, 5]])

In [60]:
A-B

array([[-1,  1],
       [ 0, -3]])

In [61]:
B**2

array([[ 4,  0],
       [ 9, 16]], dtype=int32)

In [62]:
10*np.sin(A)

array([[8.41470985, 8.41470985],
       [1.41120008, 8.41470985]])

In [63]:
A<35

array([[ True,  True],
       [ True,  True]])

In [64]:
A *= 3
A

array([[3, 3],
       [9, 3]])

In [65]:
B += A
B

array([[ 5,  3],
       [12,  7]])

In [66]:
A * B                       # elementwise product

array([[ 15,   9],
       [108,  21]])

In [67]:
A @ B                       # matrix product
#A.dot(B)                    # another matrix product

array([[51, 30],
       [81, 48]])

In [68]:
np.cross(A,B)

array([-6, 27])

np.exp(B)

In [70]:
np.sqrt(B)

array([[2.23606798, 1.73205081],
       [3.46410162, 2.64575131]])

In [76]:
# Indexing, Slicing and Iterating:-


In [77]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [78]:
a[2]

8

In [79]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [80]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [81]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000  
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [82]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [83]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
ipykernel_launcher:2: RuntimeWarning: invalid value encountered in power



## Multidimensional:-



The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].


In [84]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [85]:
b[2,3]

23

In [86]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [87]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [88]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [89]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [90]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
               [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [91]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [92]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

# Mathematical Functions

numpy.sin numpy.cos numpy.tan
numpy.exp numpy.log numpy.log10
numpy.arcsin numpy.arccos numpy.arctan

# Note

In [93]:
A = np.array( [[1,1],[3,1]] )
B = np.array( [[2,0],[3,4]] )

In [94]:
#1
x = np.array([0,0.25,0.5,0.75,1.0])
y = x**2 + 1
y

array([1.    , 1.0625, 1.25  , 1.5625, 2.    ])

In [95]:
#2
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [96]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [97]:
A[3:]+1

array([], shape=(0, 4), dtype=int32)

In [98]:
0#3
#A@A@A
from numpy.linalg import matrix_power as mpow
mpow(B,3)

array([[ 8,  0],
       [84, 64]])

In [99]:
#4
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 8., 7., 3.],
       [3., 1., 6., 7.],
       [4., 1., 8., 9.]])

In [100]:
a=np.int32(50*np.random.random((3,3)))
a

array([[ 5,  8, 37],
       [22,  4,  4],
       [12, 27, 10]])

In [105]:
a=np.array([10,11,12,10,8,9,10,2,3,10])
a

array([10, 11, 12, 10,  8,  9, 10,  2,  3, 10])

In [101]:

b=np.append(a,100)
b


array([  5,   8,  37,  22,   4,   4,  12,  27,  10, 100])

In [103]:

c=np.insert(a,0,20)
c

array([20,  5,  8, 37, 22,  4,  4, 12, 27, 10])

In [107]:
a=np.full(5,2)
a

array([2, 2, 2, 2, 2])

In [108]:
np.unique(a)

array([2])

In [109]:
np.bincount(a)

array([0, 0, 5], dtype=int64)