In [5]:
from __future__ import absolute_import, division, print_function, unicode_literals 
import tensorflow as tf 
import numpy as np
import timeit
from datetime import datetime
tf.__version__

'2.2.0'

##  1. [Tensor](https://www.tensorflow.org/guide/tensor)
In TensorFlow, a tensor is the collection of feature vector (Like, array) of n-dimension. For instance, if we have any 3x3 matrix with values 1 to 6, we write:
- Tensors are used as the basic data structures in TensorFlow language.
- Tensors represent the connecting edges in any flow diagram called the Data Flow Graph.
- Tensors are defined as multidimensional array or list.

**tf.constant()**

In [6]:
#help(tf.constant)

In [32]:
#1 Element (Rank 0)
tf.constant(4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [33]:
#1d (Rank 1)
tf.constant([2.0, 3.0, 4.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [34]:
#2d (Rank 2)
tf.constant([[2.0, 3.0, 4.0],[2.0, 3.0, 4.0],[2.0, 3.0, 4.0]])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]], dtype=float32)>

In [35]:
#3d (Rank 3)
tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

**Shape**

In [11]:
tf.constant(0, shape=(2, 3))  

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

**Type**

In [12]:
#If `dtype` is specified the resulting tensor values are cast to the requested `dtype`.
tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float64)

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([1., 2., 3., 4., 5., 6.])>

**Numpy**

In [13]:
# Or a numpy array
tf.constant(np.array([[1, 2, 3], [4, 5, 6]]))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
1. Sparse tensors

## 2. Variable

In [10]:
#help(tf.Variable)

- A TensorFlow variable is the recommended way to represent shared, persistent state your program manipulates.
- create, update, and manage instances of `tf.Variable` in TensorFlow.
- A tf.Variable represents a tensor whose value can be changed by running ops on it. 

In [22]:
#bool Variable
tf.Variable([False, False, False, True])

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [23]:
#Complex Variable
tf.Variable([5 + 4j, 6 + 1j])

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [14]:
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
variable = tf.Variable(tensor)

In [15]:
print("A variable:",variable)

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [16]:
print("Shape: ",variable.shape)

Shape:  (2, 2)


In [17]:
print("DType: ",variable.dtype)

DType:  <dtype: 'float32'>


In [18]:
print("As NumPy: ", variable.numpy)

As NumPy:  <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


In [19]:
print("Viewed as a tensor:", tf.convert_to_tensor(variable))

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [20]:
print("Index of highest value:", tf.argmax(variable))

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)


In [21]:
# This creates a new tensor; it does not reshape the variable.
print("Copying and reshaping: ", tf.reshape(variable, ([1,4])))

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


**Assign**

In [48]:
a = tf.Variable([2.0, 3.0])
b = tf.Variable(a)
a.assign([5, 6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [49]:
# a and b are different
print("A:" ,a.numpy())
print("B :",b.numpy())

A: [5. 6.]
B : [2. 3.]


In [50]:
# There are other versions of assign
print("A:", a.assign_add([2,3]).numpy())  # [7. 9.]
print("A:", a.assign_sub([7,9]).numpy())  # [0. 0.]

A: [7. 9.]
A: [0. 0.]


In [31]:
# Create a and b; they have the same value but are backed by different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")
# These are elementwise-unequal, despite having the same name
print(a == b)

NameError: name 'my_tensor' is not defined

## Variable Operation

In [74]:
a1 = tf.constant([[1, 2],
                 [3, 4]])
b1 = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`
a=tf.Variable(a1,name="NodeA")
b=tf.Variable(b1,name="NodeB")

In [75]:
# Add
#print(a+b)
#print(tf.math.add(a, b))
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [76]:
# Subtract
#print(a-b)
#print(tf.math.subtract( a, b, name=None) )
tf.subtract( a, b, name="Subtract") 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [77]:
# Multiply
#print(a*b)
tf.multiply(a, b,name="Multiply")

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [79]:
# Cross Product
#print(a @ b)
tf.matmul(a, b,name="CrossProduct") 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>

# Function

In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [ ]:
# Find the largest value
print(tf.reduce_max(c))

In [ ]:
# Find the index of the largest value
print(tf.argmax(c))

In [ ]:
# Compute the softmax
print(tf.nn.softmax(c))

In [ ]:
print(tf.sigmoid(c))

### 2.a. Graphs with tf.function

In [81]:
# Define a Python function
def function_to_get_faster(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

In [82]:
# Create a `Function` object that contains a graph
graph = tf.function(function_to_get_faster)

In [83]:
# Make some tensors
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

# It just works!
graph(x1, y1, b1).numpy()

array([[12.]], dtype=float32)

### 2.b. Graphs with Decorator

In [ ]:
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

In [ ]:
# Use the decorator
@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)

    return inner_function(x, y, b)

# Note that the callable will create a graph that
# includes inner_function() as well as outer_function()
outer_function(tf.constant([[1.0, 2.0]])).numpy()

In [ ]:
## Create run and evaluate a session  
X= tf.constant([2])  
Y= tf.constant([2])  

In [ ]:
## Create operator  
multiply = tf.multiply(X,Y)  

# CPU & GPU

In [19]:
#CPU 
with tf.device('CPU:0'):
    # Create some tensors
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [20]:
#GPU 
with tf.device('GPU:0'):
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.Variable([[1.0, 2.0, 3.0]])
    c = a * b

print(c)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
