![](_pic/TF/tflogo.png)


**What is TensorFlow?**

TensorFlow is Google’s Open Source Machine Learning Framework for dataflow programming across a range of tasks. Nodes in the graph represent mathematical operations, while the graph edges represent the multi-dimensional data arrays (tensors) communicated between them.


- "framework for numerical computation based on dataflow graphs."
- tensors - multidimensional arrays
- built in C++, used through higer level languages (Python) and libraries (keras, tf-slim)
![](_pic/TF/Tensor_Flow.png)

### 1. Tensor :
- tersor is N dimension Array
- image tensor flows through the computational graph

### 2.Flow (Computational Graph) :

- composed of nodes and edges

### Advantages and Disadvantages (a few):

- open source and continously developed
- good visualization tools 
- scalability and portability
- steeper learning curve to become good at it 
- implies solid knowledge of math
- http://tensorflow.org

### Types of Operations:

- **Operation:** Add, Sub, Div, Mul, Log, Exp, etc. (element wise math ops.)
- **on arrays and matrices :** Constant, Shape, Split, Concat, Slice, MatMul, etc.
- Sigmoid, ReLU, Convolution2D, SoftMax, etc.
- and more

Keras is an open-source neural-network library written in Python. It is capable of running on top of TensorFlow, Microsoft Cognitive Toolkit, R, Theano, or PlaidML. Designed to enable fast experimentation with deep neural networks,

## Index
01. [Installs](002.b.Install.ipynb)
02. [Tensor/Veriable/Graph](002.c.Tensor.ipynb)
03. [Perceptron](/002.d.Perceptron.ipynb)

In [ ]:
# TensorFlow 1.X
outputs = session.run(f(placeholder), feed_dict={placeholder: input})
# TensorFlow 2.0
outputs = f(input)

## Demo 1 - NN TensorFlow 1.X

In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as v1 
import tensorflow_datasets as tfds

In [2]:
g = v1.Graph()

with g.as_default():
    in_a = v1.placeholder(dtype=v1.float32, shape=(2))
    in_b = v1.placeholder(dtype=v1.float32, shape=(2))

    def forward(x):
        with v1.variable_scope("matmul", reuse=v1.AUTO_REUSE):
            W = v1.get_variable("W", initializer=v1.ones(shape=(2,2)),
                              regularizer=lambda x:tf.reduce_mean(x**2))
            b = v1.get_variable("b", initializer=v1.zeros(shape=(2)))
            return W * x + b

    out_a = forward(in_a)
    out_b = forward(in_b)
    reg_loss=v1.losses.get_regularization_loss(scope="matmul")

with v1.Session(graph=g) as sess:
  sess.run(v1.global_variables_initializer())
  outs = sess.run([out_a, out_b, reg_loss],
                feed_dict={in_a: [1, 0], in_b: [0, 1]})

print(outs[0])
print()
print(outs[1])
print()
print(outs[2])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[[1. 0.]
 [1. 0.]]

[[0. 1.]
 [0. 1.]]

1.0


# Demo - TensorFlow 2.X

In [7]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.2.0'

In [26]:
# Note: tensorflow 2.X
# module 'tensorflow' has no attribute 'placeholder'

In [25]:
# Define a Python function
def function_to_get_faster(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Create a `Function` object that contains a graph
[reseption_layer = tf.function(function_to_get_faster)

# Make some tensors
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)
# It just works!
graph(x1, y1, b1).numpy()

array([[12.]], dtype=float32)

In [8]:
x = tf.variable(tf.float32, name='X', shape=(4,9))
x

AttributeError: module 'tensorflow' has no attribute 'variable'

In [7]:
w = tf.variable(tf.float32, name='W', shape=(9,1))
b = tf.fill((4,1), -1., name='bias')
y = tf.matmul(x,w)+b
s = tf.reduce_max(y)

AttributeError: module 'tensorflow' has no attribute 'Varible'