In [ ]:
# pip install opencv-python

In [1]:
import cv2
import numpy as np
import os

In [2]:
images=[]
labels=[]
path='_dataset/Dataset-FeatureExtractionIn-Image/temp'
for i in [1,2,3]:
    for j in os.listdir( f'{path}/{i}'):
        img=cv2.imread(f'{path}/{i}/{j}',cv2.IMREAD_GRAYSCALE)
        images.append(img)
        labels.append(i)

In [3]:
X=np.array(images)
y=np.array(labels)

In [4]:
X.shape

(13784, 28, 28)

In [5]:
y.shape

(13784,)

In [6]:
X=X.reshape(len(X),-1)

In [7]:
X.shape

(13784, 784)

In [8]:
from sklearn.decomposition import PCA
pca=PCA(.99)
new_x=pca.fit_transform(X)
new_x.shape

(13784, 309)

In [9]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(new_x,y)

/media/mastersupc/WorkSpace/pyenv3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
test_img=cv2.imread('_dataset/Sample/1.png')

#### Test Sample

In [11]:
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([1])

In [12]:
test_img=cv2.imread('_dataset/Sample/2.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([2])

In [13]:
test_img=cv2.imread('_dataset/Sample/3.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([3])