# Cluster

In [2]:
from scipy.cluster.vq import kmeans,vq,whiten

## Data generation

In [ ]:
from numpy import vstack,array
from numpy.random import rand

In [5]:
# data generation with three features
data = vstack((rand(100,3) + array([.5,.5,.5]),rand(100,3)))
data

array([[1.38260911, 1.15142209, 0.94356826],
       [1.3700655 , 1.17079056, 0.95800894],
       [1.1249968 , 1.48919631, 1.37464212],
       [1.41303449, 0.61854861, 0.98185033],
       [0.61460426, 0.58651843, 1.19735889],
       [1.20870557, 1.06733178, 1.10760734],
       [1.07004122, 0.5956469 , 1.22566051],
       [0.68051188, 0.99435843, 1.49410746],
       [0.85165459, 1.25823809, 0.83814723],
       [1.20486982, 0.54688921, 0.62809069],
       [1.21892513, 1.38571495, 0.84819726],
       [1.42930401, 0.91824394, 1.0122543 ],
       [1.41891406, 0.58737329, 0.53425172],
       [0.86927125, 0.76733482, 1.34891278],
       [1.46081274, 0.88769778, 0.69968906],
       [0.64282663, 0.76214194, 0.66518151],
       [0.89461683, 1.44654982, 0.80823824],
       [1.11281669, 0.74188576, 1.44469703],
       [0.64086285, 0.91522686, 1.24746344],
       [0.57123817, 1.37636202, 0.68274725],
       [1.40629092, 1.02886901, 1.34252203],
       [0.99930309, 1.26034089, 1.34595668],
       [1.

In [7]:
data = whiten(data)

In [8]:
data

array([[3.49518955, 2.98987758, 2.34040662],
       [3.46347972, 3.04017135, 2.37622497],
       [2.84395426, 3.86696999, 3.40963304],
       [3.5721039 , 1.60617435, 2.43536064],
       [1.55369899, 1.52300214, 2.96990348],
       [3.05556721, 2.77152174, 2.74728565],
       [2.70502839, 1.54670589, 3.04010223],
       [1.72031126, 2.58203313, 3.70595233],
       [2.1529543 , 3.26724482, 2.07892255],
       [3.04587056, 1.42009764, 1.55790277],
       [3.08140193, 3.59826176, 2.10385041],
       [3.6132327 , 2.38438797, 2.51077399],
       [3.58696725, 1.52522194, 1.32514659],
       [2.19748861, 1.9925249 , 3.34581452],
       [3.6928857 , 2.30506929, 1.73549383],
       [1.62504419, 1.97904063, 1.64990204],
       [2.2615614 , 3.7562306 , 2.00473691],
       [2.81316335, 1.92644177, 3.58339575],
       [1.62007984, 2.37655356, 3.09418174],
       [1.44407098, 3.57397517, 1.69347175],
       [3.55505637, 2.67164616, 3.32996304],
       [2.52620476, 3.27270512, 3.33848228],
       [3.

In [9]:
centroids,_ = kmeans(data,3)

In [10]:
print(centroids)

[[0.63537523 1.24350589 1.0929953 ]
 [2.62327903 2.68398805 2.75668794]
 [2.03443038 1.34721    1.41083755]]


In [11]:
clx,_ = vq(data,centroids)

In [13]:
print(clx)

[1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 2
 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 2 1 1 1 2 0 2 0 0 2 2 2 2 2 2
 2 0 2 2 2 2 2 2 0 0 2 2 0 0 0 0 0 2 2 0 0 2 0 0 2 0 0 2 2 0 2 2 0 2 1 0 0
 2 2 0 0 0 0 0 2 2 0 2 0 2 0 0 2 0 1 0 0 0 0 0 0 2 0 0 2 0 0 0 0 0 0 2 0 0
 0 2 2 2 2 2 2 2 0 2 2 0 0 0 2]


# Constants Package
1	c :Speed of light in vacuum

2 speed_of_light:Speed of light in vacuum

3	 h:Planck constant

4	 Planck:Planck constant h

5 G

Newton’s gravitational constant

6	
e

Elementary charge

7	
R

Molar gas constant

8	
Avogadro

Avogadro constant

9	
k

Boltzmann constant

10	
electron_mass(OR) m_e

Electronic mass

11	
proton_mass (OR) m_p

Proton mass

12	
neutron_mass(OR)m_n

Neutron mass

In [16]:
from scipy.constants import pi
from math import pi
print("sciPy - pi = %.16f"% scipy.constants.pi)
print("math - pi = %.16f"% math.pi)

NameError: name 'scipy' is not defined