# <center>Machine Learning</center>
![](_pic/img-ML/Ml.jpg)
(ML) is the scientific study of algorithms and statistical models that computer systems use in order to perform a specific task effectively without using explicit instructions, relying on patterns and inference instead. It is seen as a subset of artificial intelligence</p>

Machine learning algorithms build a mathematical model based on sample data, known as "training data", in order to make predictions or decisions without being explicitly programmed to perform the task
 
**Need for Machine Learning**<br>
Human beings, at this moment, are the most intelligent and advanced species on earth because they can think, evaluate and solve complex problems. On the other side, AI is still in its initial stage and haven’t surpassed human intelligence in many aspects. Then the question is that what is the need to make machine learn? The most suitable reason for doing this is, “to make decisions, based on data, with efficiency and scale”.

Lately, organizations are investing heavily in newer technologies like Artificial Intelligence, Machine Learning and Deep Learning to get the key information from data to perform several real-world tasks and solve problems. We can call it data-driven decisions taken by machines, particularly to automate the process. These data-driven decisions can be used, instead of using programing logic, in the problems that cannot be programmed inherently. The fact is that we can’t do without human intelligence, but other aspect is that we all need to solve real-world problems with efficiency at a huge scale. That is why the need for machine learning arises.

**Challenges in Machines Learning**<br>
While Machine Learning is rapidly evolving, making significant strides with cybersecurity and autonomous cars, this segment of AI as whole still has a long way to go. The reason behind is that ML has not been able to overcome number of challenges. The challenges that ML is facing currently are −

   - **Quality of data** − Having good-quality data for ML algorithms is one of the biggest challenges. Use of low-quality data leads to the problems related to data preprocessing and feature extraction.

   - **Time-Consuming task** - Another challenge faced by ML models is the consumption of time especially for data acquisition, feature extraction and retrieval.

   - **Lack of specialist persons** − As ML technology is still in its infancy stage, availability of expert resources is a tough job.

   - **No clear objective for formulating business problems** − Having no clear objective and well-defined goal for business problems is another key challenge for ML because this technology is not that mature yet.

   - **Issue of overfitting & underfitting** − If the model is overfitting or underfitting, it cannot be represented well for the problem.

   - **Curse of dimensionality** − Another challenge ML model faces is too many features of data points. This can be a real hindrance.

   - **Difficulty in deployment** − Complexity of the ML model makes it quite difficult to be deployed in real life.
    
**Application of Machine learning**<br>
Agriculture, Anatomy, Adaptive websites, Affective computing, Banking, Bioinformatics, Brain–machine interfaces,      Cheminformatics, Computer Networks, Computer vision, Credit-card fraud detection, Data quality, DNA sequence classification Economics, Financial market analysis, General game playing, Handwriting recognition, Information retrieval, Insurance, Internet fraud detection, Linguistics, Machine learning control, Machine perception, Machine translation, Marketing, Medical diagnosis, Natural language processing, Natural language understanding, Online advertising, Optimization, Recommender systems, Robot locomotion, Search engines, Sentiment analysis, Sequence mining, Software engineering, Speech recognition, Structural health monitoring, Syntactic pattern recognition, Telecommunication, Theorem proving, Time series forecasting, User behavior analytics

**Machine Learning Model**<br>
Based on the above, the following diagram represents a Machine Learning Model −
![](_img/img-ML/machine_learning_model.jpg)
Before discussing the machine learning model, we must need to understand the following formal definition of ML given by professor Mitchell −

“A computer program is said to learn from experience E with respect to some class of tasks T and performance measure P, if its performance at tasks in T, as measured by P, improves with experience E.”

The above definition is basically focusing on three parameters, also the main components of any learning algorithm, namely Task(T), Performance(P) and experience (E).

ML is a field of AI consisting of learning algorithms that −
  - Improve their performance (P)
  - At executing some task (T)
  - Over time with experience (E)


Let us discuss them more in detail now −

1. **Task(T)**<br>
From the perspective of problem, we may define the task T as the real-world problem to be solved. The problem can be anything like finding best house price in a specific location or to find best marketing strategy etc. On the other hand, if we talk about machine learning, the definition of task is different because it is difficult to solve ML based tasks by conventional programming approach.
A task T is said to be a ML based task when it is based on the process and the system must follow for operating on data points. The examples of ML based tasks are Classification, Regression, Structured annotation, Clustering, Transcription etc.

2. **Experience (E)**<br>
As name suggests, it is the knowledge gained from data points provided to the algorithm or model. Once provided with the dataset, the model will run iteratively and will learn some inherent pattern. The learning thus acquired is called experience(E). Making an analogy with human learning, we can think of this situation as in which a human being is learning or gaining some experience from various attributes like situation, relationships etc. Supervised, unsupervised and reinforcement learning are some ways to learn or gain experience. The experience gained by out ML model or algorithm will be used to solve the task T.

3. **Performance (P)**<br>
An ML algorithm is supposed to perform task and gain experience with the passage of time. The measure which tells whether ML algorithm is performing as per expectation or not is its performance (P). P is basically a quantitative metric that tells how a model is performing the task, T, using its experience, E. There are many metrics that help to understand the ML performance, such as accuracy score, F1 score, confusion matrix, precision, recall, sensitivity etc.



**Terms Used in machine Learning:**
- Input/Features/Attributes/Dimensions refer to parameters (columns) of training dataset.
- Instance represents one sample of training dataset.
- Label/class/target refers output of training dataset.
- X is symbol for features and y is symbol for label
Example:
<table border="1">  
<tr><th>Age</th><th>Salary</th><th>Purchased</th></tr>  
<tr><td>44 </td><td>72000</td><td> No</td></tr> 
<tr><td>27</td><td> 48000</td><td> Yes</td></tr> 
<tr><td>30 </td><td>54000</td><td> No</td></tr> 
<tr><td>38 </td><td>61000</td><td> No</td></tr> 
<tr><td>40 </td><td>40000</td><td> Yes</td></tr> 
<tr><td>35 </td><td>58000</td><td> Yes</td></tr> 
<tr><td>42 </td><td>52000</td><td> No</td></tr> 
<tr><td>48 </td><td>79000</td><td> Yes</td></tr> 
<tr><td>50 </td><td>83000</td><td> No</td></tr> 
<tr><td>37 </td><td>67000</td><td> Yes</td></tr> 
</table>  

Here, Age and Salary are features(X) and Purchased is Label(y) and 44,72000 is
one instance of features 

### ML Process
![](_pic/img-ML/MLProcess.png)

![](_pic/img-ML/Steps-to-Predictive-Modelling.jpg)

    Step 1 − First, we need to collect all the training data for start training the model.
    Step 2 − Now, start the training of model by providing whole training data in one go.
    Step 3 − Next, stop learning/training process once you got satisfactory results/performance.
    Step 4 − Finally, deploy this trained model into production. Here, it will predict the output for new data sample.

**Python Implementation of ML:**
There are following two popular ML libraries in python:
 1. Scikit-learn
 2. Tensor flow (aka deep learning)

**Scikit-learn:**
<center>cmd-> pip install scikit-learn</center>

- It was developed by Google in 2007 and publically available from 2010 as open source library.
- You can download Scikit learn by writing following command

If you are using anaconda IDE, it is by default bundled.

- NOTE 1: This library takes features in numeric form so we must convert all features into numbers before passing data to training.

- NOTE 2: After converting features into numbers we must represents these features in 2d array or nested list. In the same way label must be represented as 1d array or list.

#### Example:-

Consider following dataset of online purchased

<table border="1">  
<tr><th>Age</th><th>Salary</th><th>Purchased</th></tr>  
<tr><td>44 </td><td>72000</td><td> No</td></tr> 
<tr><td>27</td><td> 48000</td><td> Yes</td></tr> 
<tr><td>30 </td><td>54000</td><td> No</td></tr> 
<tr><td>38 </td><td>61000</td><td> No</td></tr> 
<tr><td>40 </td><td>40000</td><td> Yes</td></tr> 
<tr><td>35 </td><td>58000</td><td> Yes</td></tr> 
<tr><td>42 </td><td>52000</td><td> No</td></tr> 
<tr><td>48 </td><td>79000</td><td> Yes</td></tr> 
<tr><td>50 </td><td>83000</td><td> No</td></tr> 
<tr><td>37 </td><td>67000</td><td> Yes</td></tr> 
</table>  

By observing above dataset we may conclude that given example belongs to classification problem of supervise learning.
- Features: Age, Salary
- Label or Target: Purchased

Now,Represents these features as 2d array and label as 1d array

In [2]:
data=[[44,72000], [27,48000],[30,540000], [38,61000], [40,40000], [35,58000],[42,52000], [48,79000], [50,83000], [37,67000]]

In [3]:
label=[0,1,0,0,1,1,0,1,0,1]

**Code:**

In [4]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(data,label)
knn.predict([[32,20000]])

array([1])

**NOTE:**
- Most of the times we do not have cleaned or prepared dataset so we must prepare dataset before passing it to training.

**Data Preprocessing:**
- Identify missing values in features
- Fill these missing values by using mean or other approach
- You may also drop a row if most of the values are missing
- Sometimes not all features are required in training ,remove those features
- Converting features and label into numeric values so that dataset can be passed to training.
- Do feature Scaling if values of features are not in same range.

## <a href="b.TrainAndTest.ipynb">Hint:Feature Selection Train Test </a>

-----------------

### Types of Learning algorithms

![](_pic/img-ML/tyMl.jpg)

The following are various ML methods based on some broad categories −

-------------

### 1.Supervised Learning

- <p>Supervised learning algorithms or methods are the most commonly used ML algorithms. This method or learning algorithm take the data sample i.e. the training data and its associated output i.e. labels or responses with each data samples during the training process.</p>

- <p>These are the algorithms that work on predictions and search for patterns on given set of samples. Supervised Machine Learning Algorithms attempt to render relationships and dependencies between the target prediction output and the input features. In this, we start from input variables (x) and an output variable (Y) and try to map functions from the input to the output so that they establish a relationship which can be used for prediction.</p>

- The main objective of supervised learning algorithms is to learn an association between input data samples and corresponding outputs after performing multiple training data instances.

For example, we have

**X(Feature)** − Input variables and

**Y(Target)** − Output variable(labeled data)

Now, apply an algorithm to learn the mapping function from the input to output as follows −

**Y=f(x)**<BR>
Now, the main objective would be to approximate the mapping function so well that even when we have new input data (x), we can easily predict the output variable (Y) for that new input data.

![](img/img-SupervisedLearning/S.png)

**Based on the ML tasks, supervised learning algorithms can be divided into following two broad classes :-**

#### 1.Regression

The key objective of regression-based tasks is to predict output labels or responses which are continues numeric values, for the given input data. The output will be based on what the model has learned in its training phase. Basically, regression models use the input data features (independent variables) and their corresponding continuous numeric output values (dependent or outcome variables) to learn specific association between inputs and corresponding outputs. We will discuss regression and associated algorithms in detail in further chapters also.

**Algo**

1. <a href="02.LinearRegression.ipynb">Linear Regression</a>
2. <a href="03.MultipleRegression.ipynb">Multiple Regression</a>
3. <a href="04.PolynomialRegression.ipynb">Polynomial Regression </a>


####  2.Classification

The key objective of classification-based tasks is to predict categorial output labels or responses for the given input data. The output will be based on what the model has learned in training phase. As we know that the categorial output responses means unordered and discrete values, hence each output response will belong to a specific class or category. We will discuss Classification and associated algorithms in detail in the upcoming chapters also.
- In machine learning and statistics, classification is a supervised learning approach in which the computer program learns from the data input given to it and then uses this learning to classify new observation. This data set may simply be bi-class (like identifying whether the person is male or female or that the mail is spam or non-spam) or it may be multi-class too. Some examples of classification problems are: speech recognition, handwriting recognition, bio metric identification, document classification etc.

- A classification problem is when the output variable is a category, such as “red” or “blue” or “disease” and “no disease”. A classification model attempts to draw some conclusion from observed values. Given one or more inputs a classification model will try to predict the value of one or more outcomes.

**Which of the following is/are classification problem(s)**

- Predicting the gender of a person by his/her handwriting style
- Predicting house price based on area
- Predicting whether monsoon will be normal next year
- Predict the number of copies a music album will be sold next month
- For example, when filtering emails “spam” or “not spam”, when looking at transaction data, “fraudulent”, or “authorized”. In short Classification either predicts categorical class labels or classifies data (construct a model) based on the training set and the values (class labels) in classifying attributes and uses it in classifying new data. 
- Predicting whether monsoon will be normal next year. The other two are regression. As we discussed classification with some examples. Now there is an example of classification in which we are performing classification on the iris dataset using RandomForestClassifier in python. You can download the dataset from Here







***Algo***

- Here we have the types of classification algorithms in Machine Learning:
    1. <a href="05.LogisticRegression.ipynb">Logistic Regression</a>
    2. <a href="06.NaiveBayes.ipynb">Naive Bayes Classifier</a>
    3. <a href="07.DecisionTree.ipynb">Decision trees </a>
    4. <a href="08.RandomForestClassifier.ipynb">Random Forest</a>
    5. <a href="09.BoostedTree.ipynb">Gradient-Boosted Tree (Boosted Trees)</a>
    6. <a href="10.KNearestNeighbor.ipynb">K Nearest Neighbor(KNN)</a>
    7. <a href="11.SupportVectorMachines.ipynb">Support Vector Machines(SVM)</a>
    8.  Multilayer Perceptron
    9.  One Vs Rest
    10. Neural Networks
        - Neural Networks (Multilayer perceptron)

**Note:-Linear Classifiers: Logistic Regression, Naive Bayes Classifier**
   - **Dimensionality Reduction**
    - PCA (Principal Component Analysis)
    - Discriminant analysis

    - linear discriminant analysis
    - Similarity learning

**Neural Network:**
<p>A neural network consists of units (neurons), arranged in layers, which convert an input vector into some output. Each unit takes an input, applies a (often nonlinear) function to it and then passes the output on to the next layer. Generally the networks are defined to be feed-forward: a unit feeds its output to all the units on the next layer, but there is no feedback to the previous layer. Weightings are applied to the signals passing from one unit to another, and it is these weightings which are tuned in the training phase to adapt a neural network to the particular problem at hand.
Machine Learning</p>


---

## 2.Unsupervised Learning

- Unsupervised learning algorithms take a set of data that contains only inputs, and find structure in the data, like grouping or clustering of data points. The algorithms therefore learn from test data that has not been labeled, classified or categorized.

- Unsupervised learning takes place when you have no labelled data available for training. It is the basic type algorithm where you only have input data and no coinciding output variables. These are called so because there is no corresponding output to a particular input. Their problems can be further grouped into clustering to discover inherent grouping and association problems.

- Examples of unsupervised machine learning algorithms includes K-means clustering, K-nearest neighbors etc.
For example, it can be understood as follows −

![](img/img-ML/uns.png)
Suppose we have,
- **x** −Input variables, then there would be no corresponding output variable and the algorithms need to discover the interesting pattern in data for learning.
- **Target** : unlabeled data.

Based on the ML tasks, unsupervised learning algorithms can be divided into following broad classes −

### a. Clustering
Clustering methods are one of the most useful unsupervised ML methods. These algorithms used to find similarity as well as relationship patterns among data samples and then cluster those samples into groups having similarity based on features. The real-world example of clustering is to group the customers by their purchasing behavior.

### b. Association
Another useful unsupervised ML method is Association which is used to analyze large dataset to find patterns which further represents the interesting relationships between various items. It is also termed as Association Rule Mining or Market basket analysis which is mainly used to analyze customer shopping patterns.

### c. Dimensionality Reduction
This unsupervised ML method is used to reduce the number of feature variables for each data sample by selecting set of principal or representative features. A question arises here is that why we need to reduce the dimensionality? The reason behind is the problem of feature space complexity which arises when we start analyzing and extracting millions of features from data samples. This problem generally refers to “curse of dimensionality”. PCA (Principal Component Analysis), K-nearest neighbors and discriminant analysis are some of the popular algorithms for this purpose.

**Algorithms:**

The most widely used learning algorithms are:

- **Clustering**
    - <a href="12.KMean.ipynb">K-means clustering(imp)</a>
    - Mean-Shift Algorithm
    - Hierarchical Clustering

- **Dimensionality Reduction**
    - PCA (Principal Component Analysis)
    - Discriminant analysis
    - K-nearest neighbors

## 3.Semi-Supervise Learning
Combination of supervise and unsupervised learning, means in sample
dataset some features are given with their labels and some features are given without labels.

## 4.Reinforcement Learning:

These algorithms forward an action according to the data point and later assess the decision. Algorithm utilises the observations collected from the interaction and take actions so as to minimise the risk and maximise the benefits. The algorithm learns in an iterative fashion. Common Algorithms that come under the reinforcement are Q-Learning, Deep Adversarial Networks, and Temporal Difference. Algorithm is applicable in the field of Game AI, skill acquisition, learning tasks, robot navigation and real-time decision.

- No features and labels are given initially
- Reward or feedback is given to an action, positive or negative moves become experience.

**Move** ->becomes features.

**Reward/feedback**->become label

Example: chess game

# <center><u>Important Topic</u></center>
#  A)  Feature Preprocessing :

In [73]:
import numpy as np
data = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

In [74]:
from sklearn import preprocessing

### 1. Scaling:

In [40]:
preprocessing.scale(data)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

- **"fit"** computes the mean and std to be used for later scaling. (jsut a computation), nothing is given to you. 

- **"transform"** uses a previously computed mean and std to autoscale the data (subtract mean from all values and then divide it by std).
- **"fit_transform"** does both at the same time.

**Scaling features to a range**

- MinMaxScaler 
- MaxAbsScaler

**Load Dataset/Clean**

### 2. MinMaxScalar :
 <center>$\begin{align*}MinRange+(MaxRange-MinRange)*(x_i-x_min)/(xmax-xmin)\end{align*}$</center>

In [41]:
scaler = preprocessing.MinMaxScaler()
#sc=MinMaxScaler(feature_range=(1,5))

In [43]:
scaler.fit(data)

MinMaxScaler()

In [44]:
scaler.data_max_

array([2., 1., 2.])

In [77]:
sc.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [79]:
sc.min_

AttributeError: 'StandardScaler' object has no attribute 'min_'

In [45]:
scaler.transform(data)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [76]:
sc.fit_transform(data)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

### 2. MaxAbsScaler :
 ## <center>$\begin{align*}\frac{x_i}{abs(x_{max})}\end{align*}$</center>

In [84]:
data

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [86]:
sc=preprocessing.MaxAbsScaler()
sc.fit_transform(data)

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

### 3. Standard Scalar :
 ## <center>$\begin{align*}\frac{x_i-x_{mean}}{std\ of\ feature}\end{align*}$</center>
 
  **full formula is:**
 
 
**X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))**

**X_scaled = X_std * (max - min) + min**

In [81]:
data

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [ ]:
import numpy as np
A=np.array([1,0,2,2,1])
std=np.std(A)
mean=np.mean(A)
(1-mean)/std

In [83]:
sc=preprocessing.StandardScaler()
sc.fit_transform(data)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

### 4. Normalizer :

**it works with row **

## <center>$\begin{align*}\frac{x_i}{(sum\ of\ square\ each\ element\ in\ row)^{2}}\end{align*}$</center>


### 5. Binarizer :
all values above threshold will be 1 and less or same will be 0

## B. [Train And Test](b.TrainAndTest.ipynb)
- Dataset Selection for Train And Test
    -  train_test_split
    -  Cross-Validated metrics
    -  K-Fold
    -  ShuffleSplit
- Train And Test Problem:
    - Fitting Problem 
    - Type of Fitting (Under Fitting and Over Fitting)
    - The Bias vs Variance trade-off
    - Regularization
    - Variance
    - Ideal Statement for a Model

<a href="b.TrainAndTest.ipynb">more....</a>

### C) Feature Extraction
    - It is a technique to extract features from a corpus(in text) or images.
    - In Text classification we need to extract feature from a corpus and in image classificaion we need to extract feature from images.
- <a href="c.i.FeatureExtractionInText.ipynb">Feature Extraction in Text</a>
- <a href="c.ii.FeatureExtractionInImage.ipynb">Feature Extraction in Image</a>


### <a href="d.ParameterTuning.ipynb">D) Parameter Tuning</a>

# <center>Performance Metrics(Parameters) for classification:</u></center>

## 1. [Confusion Matrix](e.ConfusionMatrix.ipynb)

![](_pic/img-performance/ConfusionMatrics.png)

**Terms associated with Confusion matrix:**

**1. True Positives (TP):** 

- True positives are the cases when the actual class of the data point was 1(True) and the predicted is also 1(True)

**2. True Negatives (TN):** 

- True negatives are the cases when the actual class of the data point was 0(False) and the predicted is also 0(False)

**3. False Positives (FP):**

- False positives are the cases when the actual class of the data point was 0(False) and the predicted is 1(True). False is because the model has predicted incorrectly and positive because the class predicted was a positive one. (1)

**4. False Negatives (FN):** 

- False negatives are the cases when the actual class of the data point was 1(True) and the predicted is 0(False). False is because the model has predicted incorrectly and negative because the class predicted was a negative one. (0) 

**Accuracy** measures how well the test predicts both True and Negative classes.
(Overall correctness of model) 

<center>$\begin{align*}Accuracy = \frac{TP +TN}{TP + FP + FN + TN}\end{align*}$</center>


**Sensitivity (Recall or True positive rate)** measures the proportion of positives that are correctly identified as such 
(Accuracy of class 1)

 <center>$\begin{align*}Recall =\frac{TP }{TP + FN}\end{align*}$</center>


**Specificity (True negative rate)** measures the proportion of negatives that are correctly identified as such. 
(Accuracy of class 0)

 <center>$\begin{align*}Specificity = \frac{TN}{TN + FP}\end{align*}$</center>
 
**Precision (Positive Predictive Value)** is intuitively the ability of the classifier not to label as positive a sample that is
negative.
(How Many predicted 1 are actually 1)

<center>$\begin{align*}Precision =\frac{TP }{FP + TP}\end{align*}$</center>

**Negative Predictive Value** 

<center>$\begin{align*}Negative Predictive Value =\frac{TN}{FN + TN}\end{align*}$</center>


**False Positive Rate (FPR) :**
The false positive rate is the proportion of all negatives that still yield positive test outcomes.

 <center>$\begin{align*}False Positive Rate= \frac{FP}{FP + TN}\end{align*}$</center>
 
 
**F-1 Score:**
If we have immbalanced data like in titanic we have majority of sample belonging to 0 class.

Or suppose consider:

- 100 samples(instances)->class 0

- 20 samples(instances)->class 1

The above data is immbalanced.

So ,with immbalanced data we should test model performance by using F-1 score.

<center> $\begin{align*}F1 = 2 *\frac{precision * recall}{precision + recall} \end{align*}$ </center>

**Load dataset/Clean**

In [48]:
import pandas as pd
df=pd.read_csv('_dataset/Dataset-ConfusionMatrix/Online_Ads.csv')
#hot encoding
df['Gender']=df['Gender'].map({'Male':1, 'Female':2})
X=df.loc[:,('Age','EstimatedSalary','Gender')].values
y=df.loc[:,'Purchased'].values
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       2   26            43000          0
3       2   27            57000          0
4       1   19            76000          0

**Preprocessing (Standard Scaler)**

In [52]:
from sklearn import preprocessing
sc=preprocessing.StandardScaler()
X_new=sc.fit_transform(X.astype(float))

**Model selection (Train Test Split)**

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_new,y,random_state=13)

**Model Train/Test**

In [56]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [ ]:
test_pred=log.predict(X_test)

**Score**

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,test_pred)

0.83

In [60]:
from sklearn import neighbors
knn=neighbors.KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [61]:
pred_test=knn.predict(X_test)

In [62]:
accuracy_score(y_test,pred_test)

0.9

**Confusion Matrix**

      - sklearn.metrics.confusion_matrix(y_true, y_pred)  

In [70]:
from sklearn import metrics
cm=metrics.confusion_matrix(y_test,pred_test)

In [71]:
#Mannual
tn=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]
tp=cm[1][1]

Accuracy=(tn+tp)/(tn+fp+fn+tp)
Sensitivity = Recall = TruePositiveRate = TPR =tp/(tp+fn)
Specificity=tn/(tn+fp)
Precision=tp/(fp+tp)
FalsePositiveRate= FPR = (fp/(fp + tn))
F1Score=2*(Precision*Recall)/(Precision + Recall)
print("Accuracy :"+str(Accuracy))
print("Sensitivity = Recall = TruePositiveRate = TPR :"+str(Recall))
print("Specificity :"+str(Specificity))
print("Precision :"+str(Precision))
print("FalsePositiveRate :"+str(FalsePositiveRate))
print("F1Score :"+str(F1Score))

Accuracy :0.9
Sensitivity = Recall = TruePositiveRate = TPR :0.9285714285714286
Specificity :0.8888888888888888
Precision :0.7647058823529411
FalsePositiveRate :0.1111111111111111
F1Score :0.8387096774193549


In [66]:
metrics.recall_score(y_test,pred_test)

0.9285714285714286

In [68]:
metrics.precision_score(y_test,pred_test)

0.7647058823529411

In [69]:
metrics.f1_score(y_test,pred_test)

0.8387096774193549

In [72]:
y_train.size

300