In [ ]:
## preprocessing

In [4]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [ ]:
****

In [12]:
data = np.array([[ 1., -1.,  2.],
                [ 2.,  0.,  0.],
                [ 0.,  1., -1.]])
data

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [9]:
scaler = preprocessing.StandardScaler().fit(data)
scaler 

StandardScaler()

In [10]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [11]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [13]:
X_scaled = scaler.transform(data)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [15]:
X_scaled.std(axis=0)

array([1., 1., 1.])

### 1. Scaling:

In [16]:
# help(preprocessing.scale)

In [17]:
preprocessing.scale(data)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

- **"fit"** computes the mean and std to be used for later scaling. (jsut a computation), nothing is given to you. 

- **"transform"** uses a previously computed mean and std to autoscale the data (subtract mean from all values and then divide it by std).
- **"fit_transform"** does both at the same time.

**Scaling features to a range**

- MinMaxScaler 
- MaxAbsScaler

**Load Dataset/Clean**

### 2. MinMaxScalar :
 <center>$\begin{align*}MinRange+(MaxRange-MinRange)*(x_i-x_min)/(xmax-xmin)\end{align*}$</center>

In [18]:
data

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [ ]:
# help(preprocessing.MinMaxScaler)

In [ ]:
scaler = preprocessing.MinMaxScaler()
# scaler = MinMaxScaler(feature_range=(1,5))

In [ ]:
scaler.fit(data)

scaler.data_max_

scaler.scale_

scaler.min_

data

scaler.transform(data)

scaler.fit_transform(data)

In [ ]:
**manual**

dataMax= data.max()
dataMin=data.min()
dataMax-dataMin

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min

data[0:,0].min()

### 2. MaxAbsScaler :
 ## <center>$\begin{align*}\frac{x_i}{abs(x_{max})}\end{align*}$</center>

data

sc=preprocessing.MaxAbsScaler()
sc.fit_transform(data)

### 3. Standard Scalar :
 ## <center>$\begin{align*}\frac{x_i-x_{mean}}{std\ of\ feature}\end{align*}$</center>
 
  **full formula is:**
 
 
**X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))**

**X_scaled = X_std * (max - min) + min**

data

import numpy as np
A=np.array([1,0,2,2,1])
std=np.std(A)
std

mean=np.mean(A)
(1-mean)/std

sc=preprocessing.StandardScaler()
sc.fit_transform(data)

### 4. Normalizer :

**it works with row **

## <center>$\begin{align*}\frac{x_i}{(sum\ of\ square\ each\ element\ in\ row)^{2}}\end{align*}$</center>


### 5. Binarizer :
all values above threshold will be 1 and less or same will be 0

**Fit and Transform**

In [6]:
sc.fit_transform(X_train)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [8]:
sc.scale_

array([0.5       , 0.5       , 0.33333333])

In [9]:
sc.min_ 

array([0.        , 0.5       , 0.33333333])

-0.2672612419124243

![](mg/img-FeatureScalaingPreprocessing/FS.png)