# <center> <u>Parameter Tuning </u></center>

In [2]:
import pandas as pd
df=pd.read_csv('res/Online_Ads.csv')
#df=pd.get_dummies(df)
#X=df.loc[:,('Age','EstimatedSalary','Gender_Female','Gender_Male')].values or
df['Gender']=df['Gender'].map({'Male':1, 'Female':2})
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       2   26            43000          0
3       2   27            57000          0
4       1   19            76000          0

In [2]:
X=df.loc[:,('Age','EstimatedSalary','Gender')].values
y=df.loc[:,'Purchased'].values

In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_new=sc.fit_transform(X.astype(float))
X_new

array([[-1.78179743, -1.49004624, -1.02020406],
       [-0.25358736, -1.46068138, -1.02020406],
       [-1.11320552, -0.78528968,  0.98019606],
       ...,
       [ 1.17910958, -1.46068138,  0.98019606],
       [-0.15807423, -1.07893824, -1.02020406],
       [ 1.08359645, -0.99084367,  0.98019606]])

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score


In [5]:
my_list=[]
for j in range(3,30):
    knn=KNeighborsClassifier(n_neighbors=j)
    pred_arr=cross_val_score(knn,X_new,y,cv=10,scoring='accuracy')
    mean=pred_arr.mean()
    my_list.append([j, mean] ) 
pred_arr.mean()   

0.857559412132583

In [6]:
import numpy as np
a=np.array(my_list)
X=a[:,0] # returns the third columm
Y=a[:,1]
import matplotlib.pyplot as plt
plt.plot(X,Y,c='r')
plt.scatter(X,Y,c='b')
plt.show()
Y.max()
# [10, 0.9099015009380864],
# [11, 0.9099015009380864],

<Figure size 640x480 with 1 Axes>

0.9099015009380864

In [7]:
my_list

[[3, 0.8971482176360226],
 [4, 0.8897091932457787],
 [5, 0.9073405253283301],
 [6, 0.8999624765478424],
 [7, 0.9073405253283303],
 [8, 0.89989837398374],
 [9, 0.9049015009380863],
 [10, 0.9099015009380864],
 [11, 0.9099015009380864],
 [12, 0.9074624765478424],
 [13, 0.9073373983739839],
 [14, 0.8927063789868669],
 [15, 0.8925813008130081],
 [16, 0.8829502814258913],
 [17, 0.8829502814258913],
 [18, 0.8803861788617887],
 [19, 0.8803861788617887],
 [20, 0.8779471544715447],
 [21, 0.8779471544715447],
 [22, 0.870254846779237],
 [23, 0.872693871169481],
 [24, 0.8653767979987492],
 [25, 0.8678158223889932],
 [26, 0.8626876172607881],
 [27, 0.8576844903064416],
 [28, 0.857559412132583],
 [29, 0.857559412132583]]

In [8]:
#==========================================================================================================================

In [1]:
import pandas as pd
df=pd.read_csv('res/Online_Ads.csv')
df['Gender']=df['Gender'].map({'Male':1, 'Female':2})
X=df.loc[:,('Age','EstimatedSalary','Gender')].values
y=df.loc[:,'Purchased'].values
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       2   26            43000          0
3       2   27            57000          0
4       1   19            76000          0

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_new=sc.fit_transform(X.astype(float))
X_new

array([[-1.78179743, -1.49004624, -1.02020406],
       [-0.25358736, -1.46068138, -1.02020406],
       [-1.11320552, -0.78528968,  0.98019606],
       ...,
       [ 1.17910958, -1.46068138,  0.98019606],
       [-0.15807423, -1.07893824, -1.02020406],
       [ 1.08359645, -0.99084367,  0.98019606]])

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [12]:
from sklearn.model_selection import GridSearchCV
#grid=GridSearchCV(knn,param_grid={'n_neighbors':[3,4,5,6,7]},cv=5)
grid=GridSearchCV(knn,param_grid={'n_neighbors':range(3,10)},cv=5)  #  DeprecationWarning
grid=GridSearchCV(knn,param_grid={'n_neighbors':range(3,10)},cv=5,iid=False)
grid.fit(X_new,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid=False, n_jobs=None,
       param_grid={'n_neighbors': range(3, 10)}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

In [13]:
grid.best_params_

{'n_neighbors': 9}

In [14]:
grid.best_score_

0.9048007501172057

In [15]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(knn,param_distributions={'n_neighbors':range(3,20)},cv=5,n_iter=5,iid='False')
rs.fit(X_new,y)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
          fit_params=None, iid='False', n_iter=5, n_jobs=None,
          param_distributions={'n_neighbors': range(3, 20)},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [16]:
rs.best_params_

{'n_neighbors': 10}

In [17]:
rs.best_score_

0.9075

In [18]:
#==========================================================================================================================

In [19]:
import numpy as np
a=np.arange(.01,.9,.1)
a

array([0.01, 0.11, 0.21, 0.31, 0.41, 0.51, 0.61, 0.71, 0.81])

In [20]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(solver='lbfgs', multi_class='auto')

In [21]:
grid=GridSearchCV(log,param_grid={'C':a},cv=3,iid=False)
grid.fit(X_new,y)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid=False, n_jobs=None,
       param_grid={'C': array([0.01, 0.11, 0.21, 0.31, 0.41, 0.51, 0.61, 0.71, 0.81])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [22]:
grid.best_score_

0.807176240012061

In [23]:
grid.best_params_

{'C': 0.31000000000000005}

In [24]:
#==========================================================================================================================

In [3]:
df=pd.read_csv('res/Salary_Data.csv')
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [27]:
grid=GridSearchCV(lr,param_grid={'normalize':[True,False],'fit_intercept':[True,False]},scoring='r2')
grid.fit(X,y)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'normalize': [True, False], 'fit_intercept': [True, False]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)

In [28]:
grid.best_params_

{'fit_intercept': True, 'normalize': False}

In [29]:
grid.best_score_

0.5920284587713647