In [1]:
import numpy as np

In [2]:
a=np.arange(1,13)

In [3]:
a.size

12

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
b=a.reshape(3,4)

In [6]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
a.resize(3,4)

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b=np.arange(1,13)

In [12]:
b.resize(3,4)

In [13]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
c=a+b

In [15]:
c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [19]:
d=np.hstack([a,b])

In [20]:
d

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [21]:
e=np.vstack([a,b])

In [22]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
e.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])

In [24]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
f=e.flatten()

In [26]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])

In [27]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
e.ndim

2

In [29]:
e.shape

(6, 4)

In [30]:
e.size

24

In [32]:
p=e.reshape(3,4,2)#depth,rows,cols

In [33]:
p

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [34]:
p.shape

(3, 4, 2)

In [35]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
e[e%2==0]

array([ 2,  4,  6,  8, 10, 12,  2,  4,  6,  8, 10, 12])

In [37]:
#array[row_slicing,col_slicing]

In [38]:
e[2:5,1:3]

array([[10, 11],
       [ 2,  3],
       [ 6,  7]])

In [39]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
e[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [41]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
e[:,:-1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [43]:
e[::2,:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])