In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
a=np.array([[1,20],[0,18],[2,25],[2,30],[1,25]])

In [5]:
a

array([[ 1, 20],
       [ 0, 18],
       [ 2, 25],
       [ 2, 30],
       [ 1, 25]])

In [6]:
sc=MinMaxScaler()
#sc=MinMaxScaler(feature_range=(1,5))

In [7]:
sc.fit(a)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
a1=sc.transform(a)

In [9]:
a1

array([[0.5       , 0.16666667],
       [0.        , 0.        ],
       [1.        , 0.58333333],
       [1.        , 1.        ],
       [0.5       , 0.58333333]])

In [19]:
a2=sc.fit_transform(a)

C:\Users\aditya\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
a2

array([[0.5       , 0.16666667],
       [0.        , 0.        ],
       [1.        , 0.58333333],
       [1.        , 1.        ],
       [0.5       , 0.58333333]])

In [21]:
from sklearn.preprocessing import MaxAbsScaler

In [22]:
sc=MaxAbsScaler()

In [23]:
a2=sc.fit_transform(a)

In [24]:
a2

array([[0.5       , 0.66666667],
       [0.        , 0.6       ],
       [1.        , 0.83333333],
       [1.        , 1.        ],
       [0.5       , 0.83333333]])

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc=StandardScaler()

In [27]:
a4=sc.fit_transform(a)

C:\Users\aditya\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
a4

array([[-0.26726124, -0.8523247 ],
       [-1.60356745, -1.32583843],
       [ 1.06904497,  0.33145961],
       [ 1.06904497,  1.51524392],
       [-0.26726124,  0.33145961]])

In [29]:
a

array([[ 1, 20],
       [ 0, 18],
       [ 2, 25],
       [ 2, 30],
       [ 1, 25]])

In [30]:
import numpy as np

In [31]:
A=np.array([1,0,2,2,1])

In [33]:
std=np.std(A)

In [34]:
mean=np.mean(A)

In [35]:
(1-mean)/std

-0.2672612419124243